# Generated by Django 6.0.7 on 2026-08-05 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
        ('sms_providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('sms_api_key', models.CharField(blank=True, help_text='Your API key for the selected SMS provider', max_length=500, null=True, verbose_name='SMS Provider API Key')),
                ('max_price', models.DecimalField(blank=True, decimal_places=4, help_text='Maximum price you are willing to pay for a phone number', max_digits=6, null=True, verbose_name='Max Price')),
                ('default_password', models.CharField(blank=True, max_length=10, null=True, verbose_name='Default Password')),
                ('target_accounts', models.PositiveIntegerField(blank=True, null=True, verbose_name='Target Accounts to Retrieve')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('default_country', models.ForeignKey(blank=True, help_text='Country whose phone numbers will be purchased from the SMS provider', null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.country', verbose_name='Default Country')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('sms_provider', models.ForeignKey(blank=True, help_text='Select the SMS platform to use for purchasing phone numbers', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_providers.smsprovider', verbose_name='SMS Provider')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Configuration',
                'verbose_name_plural': 'User Configurations',
                'ordering': ['-created'],
            },
        ),
    ]
