# Generated by Django 6.0.7 on 2026-08-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Maximum price you are willing to pay for a phone number', max_digits=20, null=True, verbose_name='Max Price'),
        ),
    ]
