# Generated by Django 6.0.7 on 2026-08-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userconfig_max_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='max_attempts',
            field=models.PositiveIntegerField(blank=True, help_text="Hard limit on total phone numbers tried per job, across all attempts, before it stops even if the target account count hasn't been reached. Leave blank to use the system default (10).", null=True, verbose_name='Max Phone Number Attempts'),
        ),
    ]
