# Generated by Django 6.0.7 on 2026-08-05 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('uid', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook UID')),
                ('password', models.CharField(blank=True, max_length=10, null=True, verbose_name='Facebook Password')),
                ('cookies', models.JSONField(verbose_name='Facebook Cookies')),
                ('access_token', models.TextField(blank=True, null=True, verbose_name='Access Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='jobs.flowattempt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facebook_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facebook Account',
                'verbose_name_plural': 'Facebook Accounts',
                'ordering': ['-created'],
                'unique_together': {('user', 'uid')},
            },
        ),
    ]
