"""
Django settings for pull_data project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

PROJECT_NAME = "pull_data"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m+2=921%hm9#_vpfh#y3#_h!gr)4o@c7-ku=1(%85s&$43pymb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'sorl.thumbnail',
    'widget_tweaks',
    'multiselectfield',

    'core',
    'apps.users',
    'apps.country',
    'apps.accounts',
    'apps.jobs',
    'apps.sms_providers',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        'debug': DEBUG,
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': "{0}_db".format(PROJECT_NAME),
        'USER': "{0}".format(PROJECT_NAME),
        'PASSWORD': "2+PJh#&?",
        'HOST': "127.0.0.1",
        'PORT': "5432",
        'ATOMIC_REQUESTS': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        }
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kuala_Lumpur'

USE_I18N = True

USE_L10N = False

USE_TZ = True

USE_HTTPS = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'assets/%s' % PROJECT_NAME)

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'

# Logging Settings
LOGGING_ROOT = os.path.join(BASE_DIR, 'logs')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'formatters': {
        'django.server': {
            '()': 'django.utils.log.ServerFormatter',
            'format': '[%(asctime)s] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'verbose': {
            'format': '%(levelname)s - [%(asctime)s] [%(name)s:%(lineno)s] - %(module)s - \
                %(process)d - %(thread)d - %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'simple': {
            'format': '%(levelname)s - [%(name)s:%(lineno)s] - %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'django.server': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'django.server',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        },
        'log_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGGING_ROOT, 'error.log'),
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 2,
            'formatter': 'verbose',
            # Without this, RotatingFileHandler falls back to the OS's
            # locale-preferred encoding, which on Windows is cp1252 - unable
            # to represent most non-Latin1 characters. Any log message
            # containing one (e.g. a dumped Facebook page's visible text,
            # which can include arbitrary Unicode from account names, emoji,
            # or foreign-language UI text) then raises UnicodeEncodeError
            # inside logging's own emit(), silently discarding that log
            # record entirely instead of writing it.
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'django.server': {
            'handlers': ['django.server'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['mail_admins', 'log_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        '%s' % PROJECT_NAME: {
            'handlers': ['console', 'mail_admins', 'log_file'],
            'level': 'DEBUG',
        },
    },
    # Root logger: catches every other module's logger (e.g.
    # `logging.getLogger(__name__)` in core/automation/*.py, apps/*.py),
    # since those module paths (e.g. "core.automation.facebook_recovery")
    # are NOT children of the "pull_data" logger above and would otherwise
    # only fall back to Python's silent last-resort handler.
    'root': {
        'handlers': ['console', 'log_file'],
        'level': 'INFO',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_ID = 1

# CapSolver API key for reCAPTCHA solving in browser automation
CAPSOLVER_API_KEY = "CAP-C81FE2D10589D24BD8DD02ED80A809AE6EC36CF53D5AF71155CBE880A336B277"

ADMIN_THUMB_SIZE = "x100"

# ---------------------------------------------------------------------- #
#  Celery (async job execution for the dashboard)                        #
# ---------------------------------------------------------------------- #
# Recovery jobs launch a visible (non-headless) Playwright browser and can
# run for minutes, so they must never run inside an HTTP request. The
# dashboard instead dispatches them to a Celery worker process. That worker
# needs to run on a machine with an active desktop session (same as running
# the `run_recovery_job` management command manually), since the browser
# window itself is not headless.
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://127.0.0.1:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
# Recovery jobs are long-running (potentially many minutes) - a single
# worker should only pick up one at a time so it doesn't try to juggle
# multiple visible browser windows concurrently.
CELERY_WORKER_CONCURRENCY = int(os.environ.get("CELERY_WORKER_CONCURRENCY", "1"))
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_TRACK_STARTED = True
# By default Celery "hijacks" the root logger on worker startup, replacing
# its handlers with Celery's own console-only ones. That silently wipes out
# the 'log_file' handler attached to the root logger above, which is why
# nothing logged by core.automation.facebook_recovery (or any other module
# logger that isn't a child of the "django"/PROJECT_NAME loggers) during a
# Celery-run job ever made it into logs/error.log, even though the exact
# same code logs to that file fine when run via a plain management command.
# Disabling this keeps Django's LOGGING config (including log_file) intact.
CELERY_WORKER_HIJACK_ROOT_LOGGER = False

# ---------------------------------------------------------------------- #
#  Auth (dashboard login)                                                #
# ---------------------------------------------------------------------- #
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "job_list"
LOGOUT_REDIRECT_URL = "login"