# Generated by Django 6.0.7 on 2026-08-05 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Task ID')),
                ('successful_count', models.PositiveIntegerField(default=0, verbose_name='Successul Count')),
                ('total_attempts', models.PositiveIntegerField(default=0, help_text='Total tried for this automation task', verbose_name='Total Attempts')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=50, verbose_name='Status')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed Date & Time')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Automation Job',
                'verbose_name_plural': 'Automation Jobs',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FlowAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('phone_number', models.CharField(blank=True, max_length=40, null=True, verbose_name='Phone Number')),
                ('activation_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Activation ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10, verbose_name='Flow Status')),
                ('fail_reason', models.CharField(blank=True, choices=[('no_account', 'No Facebook Account Found'), ('timeout', 'SMS Timeout'), ('wrong_length', 'Code Length not 6'), ('password_prompt', 'Facebook asked for current password'), ('other', 'Other Error')], max_length=50, null=True, verbose_name='Fail Reason')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='jobs.automationjob')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Flow Attempt',
                'verbose_name_plural': 'Flow Attempts',
            },
        ),
    ]
