# Generated by Django 6.0.7 on 2026-08-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowattempt',
            name='fail_reason',
            field=models.CharField(blank=True, choices=[('no_account', 'No Facebook Account Found'), ('timeout', 'SMS Timeout'), ('wrong_length', 'Code Length not 6'), ('password_prompt', 'Facebook asked for current password'), ('captcha_failed', 'reCAPTCHA solve failed'), ('no_sms_option', 'SMS Login Method Not Offered'), ('other', 'Other Error')], max_length=50, null=True, verbose_name='Fail Reason'),
        ),
    ]
