# Generated by Django 6.0.7 on 2026-08-11 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
        ('jobs', '0005_alter_flowattempt_fail_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationjob',
            name='country',
            field=models.ForeignKey(blank=True, help_text="Overrides the user's default country for this run only. Leave blank to use their saved default.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_jobs', to='country.country'),
        ),
        migrations.AddField(
            model_name='automationjob',
            name='target_accounts',
            field=models.PositiveIntegerField(blank=True, help_text="Overrides the user's saved target account count for this run only. Leave blank to use their saved default.", null=True, verbose_name='Target Accounts (Override)'),
        ),
    ]
