# Generated by Django 6.0.7 on 2026-08-12 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_automationjob_country_automationjob_target_accounts'),
        ('sms_providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationjob',
            name='default_password',
            field=models.CharField(blank=True, help_text="Overrides the user's saved default password for this run only. Leave blank to use their saved default.", max_length=10, null=True, verbose_name='Default Password (Override)'),
        ),
        migrations.AddField(
            model_name='automationjob',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Overrides the user's saved max price for this run only. Leave blank to use their saved default.", max_digits=20, null=True, verbose_name='Max Price (Override)'),
        ),
        migrations.AddField(
            model_name='automationjob',
            name='sms_api_key',
            field=models.CharField(blank=True, help_text="Overrides the user's saved SMS provider API key for this run only. Leave blank to use their saved default.", max_length=500, null=True, verbose_name='SMS Provider API Key (Override)'),
        ),
        migrations.AddField(
            model_name='automationjob',
            name='sms_provider',
            field=models.ForeignKey(blank=True, help_text="Overrides the user's default SMS provider for this run only. Leave blank to use their saved default.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_jobs', to='sms_providers.smsprovider', verbose_name='SMS Provider (Override)'),
        ),
    ]
