# Generated by Django 6.0.7 on 2026-08-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_automationjob_default_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationjob',
            name='error_message',
            field=models.TextField(blank=True, help_text='Summary of the last error, set when the job ends up in a failed/partial state.', null=True, verbose_name='Error Message'),
        ),
    ]
