# Generated by Django 6.0.7 on 2026-08-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_automationjob_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowattempt',
            name='fail_reason',
            field=models.CharField(blank=True, choices=[('no_account', 'No Facebook Account Found'), ('timeout', 'SMS Timeout'), ('wrong_length', 'Code Length not 6'), ('password_prompt', 'Facebook asked for current password'), ('captcha_failed', 'reCAPTCHA solve failed'), ('no_sms_option', 'SMS Login Method Not Offered'), ('otp_rejected', 'OTP Code Rejected by Facebook'), ('two_factor_required', 'Two-Factor Authenticator App Code Required'), ('phone_mismatch', 'Displayed Account/Contact Did Not Match Submitted Phone Number'), ('identify_error', "Facebook Showed 'Something Went Wrong' on Find Account Page"), ('other', 'Other Error')], max_length=50, null=True, verbose_name='Fail Reason'),
        ),
    ]
