# Generated by Django 6.0.7 on 2026-08-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_flowattempt_fail_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationjob',
            name='max_attempts',
            field=models.PositiveIntegerField(blank=True, help_text="Overrides the user's saved max attempts for this run only. Leave blank to use their saved default, or the system default (10) if they haven't set one either.", null=True, verbose_name='Max Phone Number Attempts (Override)'),
        ),
    ]
