# Generated by Django 6.0.7 on 2026-08-05 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(help_text="Human-readable name, e.g. 'Hero SMS'", max_length=100, verbose_name='Provider Name')),
                ('slug', models.SlugField(help_text="Machine-readable key used in code, e.g. 'hero-sms'", unique=True, verbose_name='Provider Slug')),
                ('website', models.URLField(blank=True, help_text="Optional link to the provider's website", null=True, verbose_name='Website')),
                ('is_active', models.BooleanField(default=True, help_text='Only active providers will appear in user configuration', verbose_name='Is Active?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'SMS Provider',
                'verbose_name_plural': 'SMS Providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderCountryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('provider_country_id', models.CharField(help_text="The ID or code used by THIS provider for this country (e.g. '4' or 'PH')", max_length=50, verbose_name="Provider's Country ID")),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_mappings', to='country.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_mappings', to='sms_providers.smsprovider')),
            ],
            options={
                'verbose_name': 'Provider Country Mapping',
                'verbose_name_plural': 'Provider Country Mappings',
                'ordering': ['provider', 'country'],
                'unique_together': {('provider', 'country')},
            },
        ),
    ]
